// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250712092951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Test Kayıtı",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 11",
                            Price = 25000m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Test Kayıtı",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone 12",
                            Price = 35000m,
                            Stock = 11
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Test Kayıtı",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "Iphone 13",
                            Price = 45000m,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Test Kayıtı",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 65000m,
                            Stock = 13
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Test Kayıtı",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 75000m,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Test Kayıtı",
                            ImageUrl = "6.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 85000m,
                            Stock = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
